#!/usr/bin/env python3

import sys, os

# Find the folder where libvcsx.py actually lives
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))

# If this is a symlink in /usr/local/bin, resolve to the real location
REAL_DIR = os.path.dirname(os.path.realpath(os.readlink(__file__))) if os.path.islink(__file__) else SCRIPT_DIR

# Add that folder to Python path
sys.path.insert(0, REAL_DIR)

import libvcsx
libvcsx.main()
